---
title: "Mapping"
author: "Jens Daniel Müller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  workflowr::wflow_html:
    number_sections: true
    toc_depth: 3
    toc_float:
      collapsed: false
editor_options:
  chunk_output_type: console
---

```{r global_options, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

```{r library, message=FALSE, warning=FALSE}
library(tidyverse)
library(reticulate)
```



```{r ggplot_theme, include = FALSE}
theme_set(theme_bw())
```


```{r install_required_python_packages_from_r, eval=FALSE}

# the commands below must only be run once, when you first run the python code and need to install required packages

# py_install("pandas")
# py_install("numpy")
# py_install("shapely")
# py_install("math")

```


```{r create_test_data_frame}

df <- tibble(LATITUDE = 30,
             LONGITUDE = -20,
             SALNTY = 35,
             THETA = 10,
             CTDPRS = 3)

source_python(here::here("analysis/python_scripts",
                         "Gamma_GLODAP_python.py"))

calculate_gamma(df)


```

