---
title: "Analysis of Cant estimates"
author: "Jens Daniel Müller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  workflowr::wflow_html:
    number_sections: true
    toc_depth: 3
    toc_float:
      collapsed: false
editor_options:
  chunk_output_type: console
---

```{r global_options, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

```{r library, message=FALSE, warning=FALSE}
library(tidyverse)
library(lubridate)
```


```{r read_parameters, include = FALSE}
parameters <-
  read_csv(here::here("data/parameters",
                      "parameters.csv"))
depth_levels <-
  read_lines(here::here("data/parameters",
                        "depth_levels.txt"))
slabs_Atl <-
  read_lines(here::here("data/parameters",
                        "slabs_Atl.txt"))
slabs_Ind_Pac <-
  read_lines(here::here("data/parameters",
                        "slabs_Ind_Pac.txt"))
```

```{r read_mask_files, include = FALSE}
basinmask <-
  read_csv(
    here::here(
      "data/World_Ocean_Atlas_2018/_summarized_files",
      "basin_mask_WOA18.csv"
    )
  )
landmask <-
  read_csv(
    here::here(
      "data/World_Ocean_Atlas_2018/_summarized_files",
      "land_mask_WOA18.csv"
    )
  )
```

```{r read_functions, include = FALSE}
source(here::here("code", "plotting_functions.R"))
```

```{r ggplot_theme, include = FALSE}
theme_set(theme_bw())
```

# Data sources

## Sabine 2004

```{r read_Sabine_Cant_file}

Cant_94 <- read_csv(here::here("data/GLODAPv1_1/_summarized_files",
                               "Cant_94.csv"))

Cant_94_inv <-
  read_csv(here::here("data/GLODAPv1_1/_summarized_files",
                      "Cant_94_inv.csv"))


```

## Gruber 2019

```{r read_Gruber_Cant_file}

Cant_07 <- read_csv(here::here("data/Gruber_2019/_summarized_files",
                               "Cant_07.csv"))

Cant_07_inv <-
  read_csv(here::here("data/Gruber_2019/_summarized_files",
                      "Cant_07_inv.csv"))

```

# Comparison of previous estimates

Cant inventory estimates of S04 (Sabine et al, 2004) and G19 (Gruber et al, 2019) were compared.

## Merge data sets

```{r merge_Cant_data_sets}

Cant_94_inv <- Cant_94_inv %>% 
  select(-cant_inv) %>% 
  rename(cant_inv = cant_inv_pos)


Cant_inv <- full_join(Cant_07_inv %>% mutate(estimate = "G19"),
                      Cant_94_inv %>% mutate(estimate = "S04"))

rm(Cant_07_inv, Cant_94_inv)

```

## Inventory maps

Spanning different time periods, the Cant inventories differ in magnitude.

```{r Cant_inv_comparison, fig.asp=1}
 
Cant_inv %>%
  ggplot() +
  geom_raster(data = landmask %>% filter(region == "land"),
              aes(lon, lat),
              fill = "grey80") +
  geom_raster(aes(lon, lat, fill = cant_inv)) +
  coord_quickmap(expand = 0) +
  scale_fill_viridis_c() +
  facet_wrap( ~ estimate, ncol = 1) +
  theme(
    axis.title = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank()
  )

```

## Relative inventories


```{r calculate_Cant_inv_ratio}


Cant_inv_wide <- Cant_inv %>%
  pivot_wider(values_from = cant_inv,
              names_from = estimate)

Cant_inv_wide <- Cant_inv_wide %>% 
  drop_na() %>% 
  mutate(G19_rel = G19 / sum(G19),
         S04_rel = S04 / sum(S04),
         cant_ratio = G19 / S04,
         cant_ratio_rel = G19_rel / S04_rel)


Cant_inv_rel <- Cant_inv_wide %>% 
  pivot_longer(cols = c(G19_rel, S04_rel),
                        names_to = "estimate",
                        values_to = "cant_inv_rel")

```



```{r Cant_inv_rel_maps, fig.asp=1}

Cant_inv_rel %>%
  ggplot() +
  geom_raster(data = landmask %>% filter(region == "land"),
              aes(lon, lat),
              fill = "grey80") +
  geom_raster(aes(lon, lat, fill = cant_inv_rel)) +
  coord_quickmap(expand = 0) +
  scale_fill_viridis_c() +
  facet_wrap( ~ estimate, ncol = 1) +
  theme(
    axis.title = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank()
  )

```

## Relative inventory ratios

```{r Cant_inv_ratio_map, fig.asp=0.6}

Cant_inv_wide %>%
  filter(cant_ratio_rel < 10,
         cant_ratio_rel > 0.1) %>% 
  ggplot() +
  geom_raster(data = landmask %>% filter(region == "land",
                                         lat <= 65,
                                         lat >= -80),
              aes(lon, lat),
              fill = "grey80") +
  geom_contour_filled(aes(lon, lat, z = log10(cant_ratio_rel))) +
  coord_quickmap(expand = 0) +
  scale_fill_brewer(palette = "RdBu", direction = -1) +
  labs(title = "Cant inventory distribution | 1994-2007 vs preind-1994",
       subtitle = "Ratio of relative contributions to total inventory") +
  theme(
    axis.title = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    legend.title = element_blank()
  )

```

