---
title: "Parameterization"
author: "Jens Daniel Müller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  workflowr::wflow_html:
    number_sections: true
    toc_depth: 3
    toc_float:
      collapsed: false
editor_options:
  chunk_output_type: console
---

```{r global_options, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

```{r library, message=FALSE, warning=FALSE}
library(tidyverse)
library(knitr)
library(kableExtra)
```

```{r ggplot_theme, include = FALSE}
theme_set(theme_bw())
```


# Definition

```{r define_parameters}


parameters <-
  lst(
    flag_f = 2,
    flag_qc = 1,
    depth_min = 150,
    bottomdepth_min = 500,
    lat_max = 65,
    year_JGOFS_start = 1981,
    year_JGOFS_end = 1999,
    year_GOSHIP_end = 2012,
    lon_Atl_section = 335.5,
    lon_Pac_section = 190.5,
    lon_Ind_section = 70.5,
    lat_Atl_profile = 40.5,
    inventory_depth = 3000,
    coarse_grid_resolution = 10,
    cruises_meridional = 1041,
    predictors_max = 5,
    predictors_min = 2,
    MLR_number = 10,
    
    depth_levels = c(0, 100, 500, 2000)
    
  )


slabs_Atl <-
  c(
    -Inf,
    26.00,
    26.50,
    26.75,
    27.00,
    27.25,
    27.50,
    27.75,
    27.85,
    27.95,
    28.05,
    28.10,
    28.15,
    28.20,
    Inf
  )

slabs_Ind_Pac <-
  c(-Inf,
    26.00,
    26.50,
    26.75,
    27.00,
    27.25,
    27.50,
    27.75,
    27.85,
    27.95,
    28.05,
    28.10,
    Inf)

```

# Overview

Following parameterizations were chosen to run the analysis and display results:

```{r print_parameter_table}
parameters

# parameters_long <-
#   parameters %>%
#   pivot_longer(1:length(parameters),
#                names_to = "parameter",
#                values_to = "value") %>%
#   arrange(parameter)
# 
# kable(parameters_long) %>%
#   kable_styling()
# 
# depth_levels
# 
# slabs_Atl
# 
# slabs_Ind_Pac

```



# Write file


```{r write_parameters}

parameters %>%
  write_rds(here::here("data/parameters",
                       "parameters.rds"))
# 
# 
# parameters %>%
#   write_csv(here::here("data/parameters",
#                        "parameters.csv"))
# 
# depth_levels %>%
#   write_lines(here::here("data/parameters",
#                          "depth_levels.txt"))
# 
# slabs_Atl %>%
#   write_lines(here::here("data/parameters",
#                          "slabs_Atl.txt"))
# 
# slabs_Ind_Pac %>%
#   write_lines(here::here("data/parameters",
#                          "slabs_Ind_Pac.txt"))

```
