---
title: "Data base"
author: "Jens Daniel Müller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  workflowr::wflow_html:
    number_sections: true
    toc_depth: 3
    toc_float:
      collapsed: false
editor_options:
  chunk_output_type: console
---

```{r global_options, include = FALSE}
knitr::opts_chunk$set(warning=FALSE, message=FALSE)
```

```{r library, message=FALSE, warning=FALSE}
library(tidyverse)
library(lubridate)
```


```{r ggplot_theme, include = FALSE}
theme_set(theme_bw())
```

# Reading original data

The file `GLODAPv2.2020_Merged_Master_File.csv` from [glodap.info](https://www.glodap.info/) was used.

Only rows which have at least one `talk` or `tco2` observation were subsetted. 

```{r rewrite_GLODAP_master_file, eval=FALSE}

GLODAP <- read_csv(here::here("data", "GLODAPv2.2020_Merged_Master_File.csv"),
                   na = "-9999",
                   col_types = cols(.default = col_double()))

# relevant columns
GLODAP <- GLODAP %>% 
  select(cruise:talkqc)

# select rows with tco2, good flag
GLODAP_clean <- GLODAP %>% 
  filter(!is.na(tco2))

GLODAP_clean <- GLODAP_clean %>% 
  filter(tco2f == "2")

GLODAP_clean <- GLODAP_clean %>% 
  filter(tco2qc == "1")


# select rows with talk, good flag

GLODAP_clean <- GLODAP_clean %>% 
  filter(!is.na(talk))

GLODAP_clean <- GLODAP_clean %>% 
  filter(talkf == "2")

GLODAP_clean <- GLODAP_clean %>% 
  filter(talkqc == "1")


# select rows with talk, good flag

GLODAP_clean <- GLODAP_clean %>% 
  filter(!is.na(phosphate))

GLODAP_clean <- GLODAP_clean %>% 
  filter(phosphatef == "2")

GLODAP_clean <- GLODAP_clean %>% 
  filter(phosphateqc == "1")


# date and decade column
GLODAP_clean <- GLODAP_clean %>% 
  mutate(date = ymd(paste(year, month, day)),
         decade = as.factor(floor(year / 10) * 10))

GLODAP_clean  %>%  write_csv(here::here("data/_summarized_data_files", "GLODAPv2.2020_Merged_Master_File_clean.csv"))

```

# Overview GLODAPv2-2020

Saptio-temporal distribution of paired `talk`, `tco2`, and `phosphate` data.

```{r reopen_GLODAP}

GLODAP <- read_csv(here::here("data/_summarized_data_files",
                              "GLODAPv2.2020_Merged_Master_File_clean.csv"),
                   guess_max = 1e5)

GLODAP <- GLODAP %>% 
  mutate(decade = as.factor(decade))

```

## Gridding

```{r spatial_gridding}

GLODAP <- GLODAP %>% 
  mutate(lat_grid = cut(latitude, seq(-90, 90, 5), seq(-87.5, 87.5, 5)),
         lat_grid = as.numeric(as.character(lat_grid)),
         lon_grid = cut(longitude, seq(-180, 180, 5), seq(-177.5, 177.5, 5)),
         lon_grid = as.numeric(as.character(lon_grid)))

GLODAP_map_year <- GLODAP %>% 
  group_by(year, lat_grid, lon_grid) %>% 
  tally() %>% 
  ungroup()

GLODAP_map_decade <- GLODAP %>% 
  group_by(decade, lat_grid, lon_grid) %>% 
  tally() %>% 
  ungroup()

GLODAP_hovmoeller_year <- GLODAP %>% 
  group_by(year, lat_grid) %>% 
  tally() %>% 
  ungroup()


```

## Histograms

```{r histogramm_observations}

GLODAP %>% 
  ggplot(aes(latitude, fill=decade))+
  geom_histogram(binwidth = 10, col="black", boundary = 0)+
  scale_x_continuous(breaks = seq(-85,90,10))+
  scale_fill_viridis_d()+
  coord_flip(expand = 0)+
  labs(title = "paired tco2 + talk + phosphate observations")

```

## Hovmoeller (Lat-time)

```{r Coverage_Hovmoeller}

GLODAP_hovmoeller_year %>% 
  ggplot(aes(year, lat_grid, fill=log10(n)))+
  geom_raster()+
  scale_fill_viridis_c(option = "magma")

```


## Maps

```{r coverage_maps_decade}

mapWorld <- borders("world", colour="gray60", fill="gray60")

GLODAP_map_decade %>%
  ggplot(aes(lon_grid, lat_grid, fill=log10(n)))+
  mapWorld+
  geom_raster()+
  scale_fill_viridis_c(option = "magma")+
  scale_x_continuous(breaks = seq(-180, 180, 30))+
  scale_y_continuous(breaks = seq(-90, 90, 30))+
  coord_quickmap(expand = FALSE)+
  facet_wrap(~decade)

```

```{r coverage_maps_year, fig.asp=2}

GLODAP_map_year %>%
  filter(year > 1990) %>% 
  ggplot(aes(lon_grid, lat_grid, fill=log10(n)))+
  mapWorld+
  geom_raster()+
  scale_fill_viridis_c(option = "magma")+
  coord_quickmap(expand = FALSE)+
  facet_wrap(~year, ncol = 5)+
  theme(axis.title = element_blank(),
        axis.text = element_blank())

```

