---
title: "Mapping"
author: "Jens Daniel Müller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  workflowr::wflow_html:
    number_sections: true
    toc_depth: 3
    toc_float:
      collapsed: false
editor_options:
  chunk_output_type: console
---

```{r global_options, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

```{r library, message=FALSE, warning=FALSE}
library(tidyverse)
library(lubridate)
library(oce)
```


```{r ggplot_theme, include = FALSE}
theme_set(theme_bw())
```

# Required data

Required are: 

- GLODAPv2_2016b_MappedClimatologies: 
- World Ocean Atlas 2018: 

```{r load_GLODAPv2_2016b_MappedClimatologies}

variables <- c("NO3", "oxygen", "PO4", "silicate")

for (i_variable in variables) {
  
  #i_variable <- variables[2]
  print(i_variable)
  temp <- read_csv(
    here::here("data/GLODAPv2_2016b_MappedClimatologies/_summarized_files",
               paste(i_variable,".csv", sep = "")))
  
  if (exists("GLODAP_predictors")) {
     GLODAP_predictors <- full_join(GLODAP_predictors, temp)
  }
  
  if (!exists("GLODAP_predictors")) {
    GLODAP_predictors <- temp
  }

}

rm(temp, i_variable, variables)

GLODAP_depths <- unique(GLODAP_predictors$depth)

```

```{r load_WOA18}

WOA18_predictors <-
  read_csv(here::here("data/World_Ocean_Atlas_2018/_summarized_files",
                       "WOA18_predictors.csv"))

WOA18_predictors <- WOA18_predictors %>% 
  rename(salinity = s_an, temperature = t_an)

WOA18_depths <- unique(WOA18_predictors$depth)


```

# Join predictor climatologies

**CAVEAT**: Coverage of GLODAP climatologies differs slightly for parameters (some are NA in some regions)

```{r join_WOA_GLODAP_predictors, fig.asp=0.5}

predictors <- full_join(GLODAP_predictors, WOA18_predictors)
rm(GLODAP_predictors, WOA18_predictors)

predictors <- predictors %>% 
  group_by(lat, lon) %>% 
  mutate(n_NO3 = sum(!is.na(NO3)),
         n_oxygen = sum(!is.na(oxygen)),
         n_PO4 = sum(!is.na(PO4)),
         n_silicate = sum(!is.na(silicate)),
         n_salinity = sum(!is.na(salinity)),
         n_temperature = sum(!is.na(temperature))) %>% 
  ungroup()

predictors <- predictors %>% 
  filter(n_NO3 > 1,
         n_oxygen > 1,
         n_PO4 > 1,
         n_silicate > 1, 
         n_salinity > 1, 
         n_temperature > 1) %>% 
  select(-c(n_NO3 , n_oxygen , n_PO4 , n_silicate , n_salinity , n_temperature))

predictors %>%
  ggplot(aes(lon, lat)) +
  geom_bin2d(binwidth = c(1,1)) +
  scale_fill_viridis_c(direction = -1) +
  coord_quickmap(expand = 0) +
  theme(legend.position = "bottom")

predictors %>%
  filter(depth == 0) %>% 
  ggplot(aes(lon, lat, fill = PO4)) +
  geom_raster() +
  scale_fill_viridis_c() +
  coord_quickmap(expand = 0) +
  theme(legend.position = "bottom") +
  labs(title = "Surface values")

predictors %>%
  filter(depth == 0) %>% 
  ggplot(aes(lon, lat, fill = temperature)) +
  geom_raster() +
  scale_fill_viridis_c() +
  coord_quickmap(expand = 0) +
  theme(legend.position = "bottom") +
  labs(title = "Surface values")


```

## Vertically interpolate WOA18

```{r interpolate_vertically}

predictors <- predictors %>% 
  group_by(lat, lon) %>% 
  arrange(depth) %>% 
  mutate(temperature = approxfun(depth, temperature, rule = 2)(depth),
         salinity = approxfun(depth, salinity, rule = 2)(depth)) %>% 
  ungroup()


predictors <- predictors %>% 
  filter(depth %in% GLODAP_depths)


```

### Predictor profiles

```{r predictor_profiles_N_Atl}

N_Atl <- predictors %>% 
  filter(lat == 40.5, lon == -20.5)

N_Atl <- N_Atl %>% 
  pivot_longer(NO3:temperature, names_to = "parameter", values_to = "value")

N_Atl %>% 
  ggplot(aes(value, depth)) +
  geom_path() +
  geom_point() +
  scale_y_reverse() +
  facet_wrap(~parameter, scales = "free_x")

```

# Neutral density slabs

```{r calculate_neutral_density_test, fig.asp=0.5}

GLODAP <- read_csv(here::here("data/GLODAPv2_2020/_summarized_data_files",
                                "GLODAP_MLR_fitting_ready.csv"))

cruises_meridional <- c("1041")

GLODAP_cruise <- GLODAP %>% 
  filter(cruise %in% cruises_meridional)


GLODAP_cruise <- GLODAP_cruise %>% 
  mutate(gamma_calc = swRho(salinity = salinity,
                            temperature = temperature,
                            pressure = depth,
                            longitude = lon,
                            latitude = lat,
                            eos = "gsw"))


GLODAP_cruise <- GLODAP_cruise %>% 
  mutate(gamma_calc = gamma_calc - 1000,
         delta_gamma = gamma - gamma_calc)


lat_section <- 
GLODAP_cruise %>%
  ggplot(aes(lat, depth)) +
  scale_y_reverse() +
  scale_color_viridis_c() +
  theme(legend.position = "bottom")

lat_section +
  geom_point(aes(col = gamma))

lat_section +
  geom_point(aes(col = gamma_calc))

lat_section +
  geom_point(aes(col = delta_gamma))

```

