---
title: "GLODAPv2_2016_Mappedclimatologies"
author: "Jens Daniel Müller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  workflowr::wflow_html:
    number_sections: true
    toc_depth: 3
    toc_float:
      collapsed: false
editor_options:
  chunk_output_type: console
---

```{r global_options, include = FALSE}
knitr::opts_chunk$set(warning=FALSE, message=FALSE)
```

```{r library, message=FALSE, warning=FALSE}
library(tidyverse)
library(lubridate)
library(tidync)
library(stars)
library(metR)
library(patchwork)
```


```{r ggplot_theme, include = FALSE}
theme_set(theme_bw())
```

# Read ncdf, write csv, plot

- Data source: [glodap.info](https://www.glodap.info/)


```{r read_GLODAPv2_2016_Mappedclimatologies_netcdfs}

file_list <- list.files(path= "data/GLODAPv2_2016b_Mappedclimatologies", pattern = "*.nc")

print("files used:")
print(file_list)

#file <- file_list[1]

for (file in file_list) {
 
clim_stars <- read_stars(here::here("data/GLODAPv2_2016b_Mappedclimatologies",
                          file))

parameter <- str_split(file, pattern = "6b.", simplify = TRUE)[2]
parameter <- str_split(parameter, pattern = ".nc", simplify = TRUE)[1]

map_clim_stars <- clim_stars %>% select(all_of(parameter))

map_clim_stars %>% 
  as_tibble() %>% 
  write_csv(here::here("data/GLODAPv2_2016b_MappedClimatologies/_summarized_files",
                       paste(parameter,".csv", sep = "")))

map_clim_stars_horizons <- map_clim_stars %>% 
  filter(depth_surface %in% c(0,50,100,200,500,1000,2000,3000,5000))

print(
ggplot()+
  geom_stars(data = map_clim_stars_horizons)+
  geom_vline(xintercept = c(190.5,335.5), col="white")+
  scale_fill_viridis_b(n.breaks = 8)+
  labs(title = file)+
  facet_wrap(~depth_surface, ncol = 3)+
  theme(#axis.text = element_blank(),
        axis.title = element_blank(),
        axis.ticks = element_blank())+
  coord_quickmap(expand = 0)
)

Atl_section <- map_clim_stars %>% 
  as_tibble() %>% 
  filter(x == 335.5)

names(Atl_section) <- c("x","y","depth_surface","parameter")

Atl_section_bathy <- Atl_section %>% 
  filter(is.na(parameter)) %>% 
  group_by(y) %>% 
  summarise(depth_surface = min(depth_surface)) %>% 
  ungroup()

p_Atl_section <-
ggplot()+
  geom_contour_fill(data = Atl_section,
                    aes(y, depth_surface, z=parameter),
                    na.fill = TRUE)+
  geom_ribbon(data = Atl_section_bathy,
              aes(x = y, ymin = depth_surface, ymax = 5500),
              fill = "grey80",
              col="black")+
  labs(title = "Atlantic ocean N-S section")+
  scale_y_reverse()+
  scale_fill_viridis_b(name = parameter,
                       n.breaks = 8)+
  coord_cartesian(expand = 0)

Pac_section <- map_clim_stars %>% 
  as_tibble() %>% 
  filter(x == 190.5)

names(Pac_section) <- c("x","y","depth_surface","parameter")

Pac_section_bathy <- Pac_section %>% 
  filter(is.na(parameter)) %>% 
  group_by(y) %>% 
  summarise(depth_surface = min(depth_surface)) %>% 
  ungroup()

p_Pac_section <-
ggplot()+
  geom_contour_fill(data = Pac_section,
                    aes(y, depth_surface, z=parameter),
                    na.fill = TRUE)+
  geom_ribbon(data = Pac_section_bathy,
              aes(x = y, ymin = depth_surface, ymax = 5500),
              fill = "grey80",
              col="black")+
  labs(title = "Pacific ocean N-S section")+
  scale_y_reverse()+
  scale_fill_viridis_b(name = parameter,
                       n.breaks = 8)+
  coord_cartesian(expand = 0)

print(
p_Atl_section / p_Pac_section
)

# clim_tidync <- tidync(here::here("data/GLODAPv2_2016b_Mappedclimatologies",
#                                  file))
# print(clim_tidync)
# 
# Atl_sec_clim <- clim_tidync %>% hyper_filter(lon = lon == 335.5)
# Atl_sec_clim_tibble <- Atl_sec_clim %>% hyper_tibble()
# 
# Atl_sec_clim_tibble %>% 
#   ggplot(aes(lat, depth_surface, fill=Cant))+
#   geom_point()+
#   scale_y_reverse()+
#   scale_fill_viridis_b()

}


```

# Plot Cant section

```{r Cant_section, eval=FALSE}

Cant <-   read_csv(here::here("data/GLODAPv2_2016b_MappedClimatologies/_summarized_files",
                              "Cant.csv"))

Cant_Atl_section <- Cant %>% 
  filter(x == 335.5)

Cant_Atl_section_bathy <- Cant_Atl_section %>% 
  filter(is.na(Cant)) %>% 
  group_by(y) %>% 
  summarise(depth_surface = min(depth_surface)) %>% 
  ungroup()

ggplot()+
  geom_contour_fill(data = Cant_Atl_section,
                    aes(y, depth_surface, z=Cant),
                    na.fill = TRUE)+
  geom_ribbon(data = Cant_Atl_section_bathy,
              aes(x = y, ymin = depth_surface, ymax = 5500),
              fill = "grey30",
              col="black")+
  scale_y_reverse()+
  scale_fill_viridis_b(breaks = seq(0,100,10))+
  coord_cartesian(expand = 0)


```


# Open tasks

- none

# Questions

- none
