---
title: "World Ocean Atlas 2018"
author: "Jens Daniel Müller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  workflowr::wflow_html:
    number_sections: true
    toc_depth: 3
    toc_float:
      collapsed: false
editor_options:
  chunk_output_type: console
---

```{r global_options, include = FALSE}
knitr::opts_chunk$set(warning=FALSE, message=FALSE)
```

```{r library, message=FALSE, warning=FALSE}
library(tidyverse)
library(lubridate)
library(tidync)
library(stars)
```


```{r ggplot_theme, include = FALSE}
theme_set(theme_bw())
```

# Data source
- Data source: [World Ocean Atlas 2018](https://www.nodc.noaa.gov/OC5/woa18/woa18data.html)

# Basin mask

## Read data

```{r read_basin_mask}

basinmask_01 <- read_csv("data/World_Ocean_Atlas_2018/basinmask_01.msk",
    skip = 1)

basinmask_01 <- basinmask_01 %>% 
  select(Latitude:Basin_0m) %>% 
  mutate(Basin_0m = as.factor(Basin_0m))

# basinmask_01_long <- basinmask_01 %>% 
#   pivot_longer(Basin_0m:Basin_3000m, values_to = "basin_ID", names_to = "depth") %>% 
#   mutate(basin_ID = as.factor(basin_ID))

```

## Assign labels

According to [WOA FAQ](https://www.nodc.noaa.gov/OC5/WOD/wod-woa-faqs.html):

1 - Atlantic Ocean
10 - Southern Ocean, between 63°W and 20°E longitudes

The Pacific:
2 - Pacific Ocean
10 - Southern Ocean, between 147°E and 63°W

The Indian:
3 - Indian Ocean
10 - Southern Ocean, between 20°E and 147°E. 

```{r basins}

basinmask_01 <- basinmask_01 %>% 
  filter(Basin_0m %in% c("1", "2", "3", "10"))
  #mutate(Basin_0m = if_else(Basin_0m %in% c("1", "2", "3", "10"), Basin_0m, "NA"))

```



## Plot

```{r basin_mask}

basinmask_01 %>% 
  ggplot(aes(Longitude, Latitude, fill=Basin_0m))+
  geom_raster()+
  coord_quickmap()

```



# Read/plot ncdf files

- read-in not yet started

```{r read_GLODAPv2_2016_Mappedclimatologies_netcdfs, eval=FALSE}

file_list <- list.files(path= "data/GLODAPv2_2016b_Mappedclimatologies", pattern = "*.nc")

print("files used:")
print(file_list)

#file <- file_list[1]

for (file in file_list) {
 
clim_stars <- read_stars(here::here("data/GLODAPv2_2016b_Mappedclimatologies",
                          file))

parameter <- str_split(file, pattern = "6b.", simplify = TRUE)[2]
parameter <- str_split(parameter, pattern = ".nc", simplify = TRUE)[1]

map_clim_stars <- clim_stars %>% select(all_of(parameter))

map_clim_stars <- map_clim_stars %>% 
  filter(depth_surface %in% c(0,50,100,200,500,1000,2000,3000,5000))

print(
ggplot()+
  geom_stars(data = map_clim_stars)+
  geom_vline(xintercept = 335, col="white")+
  scale_fill_viridis_b()+
  labs(title = file)+
  facet_wrap(~depth_surface, ncol = 3)+
  theme(axis.text = element_blank(),
        axis.title = element_blank(),
        axis.ticks = element_blank())+
  coord_quickmap(expand = 0)
)


# clim_tidync <- tidync(here::here("data/GLODAPv2_2016b_Mappedclimatologies",
#                                  file))
# print(clim_tidync)
# 
# Atl_sec_clim <- clim_tidync %>% hyper_filter(lon = lon == 335.5)
# Atl_sec_clim_tibble <- Atl_sec_clim %>% hyper_tibble()
# 
# Atl_sec_clim_tibble %>% 
#   ggplot(aes(lat, depth_surface, fill=Cant))+
#   geom_point()+
#   scale_y_reverse()+
#   scale_fill_viridis_b()

}


```


# Open tasks

- none

# Questions

- none
